* Because calling the then method of a promise returns a new derived promise, it is easily possible to create a chain of promises.
* Generally, promise handling is simple in Angular – need is a success handler and an error handler. However, a great feature of promises is the ability to chain handlers.

```js
articleService.getArticles('angular').then(function(articles){
        return articles.length;
});
```

It turns out that can be easily extend this by continuing the chain by tacking on a second then:

```javascript
articleService.getArticles('angular')
    .then(function(articles){
        return articles.length;
    })
    .then(function(count){
        //count is equal to articles.length here since the derived promise was resolved with the article count
        console.log(count);
    });
    
  ```
* starting with the initial promise returned by getArticles(). 
* Down the chain, each then invocation returns a new derived promise that becomes part of the chain. 
* Each derived promise is resolved with the return value of each then function.

```js
articleService.getArticles('angular')
    .then(function(articles){
        return articles.length;
    })
    .then(function(count){
        //count is equal to articles.length here since the promise was resolved with the count
        console.log(count);
    })
    .then(function(data){
        //data is undefined here since the promise was resolved with an undefined value
        console.log(data);
        return articleService.getArticles('javascript');
    });
    
    ```
    
Aside from the undefined data value in the third then function there is more going on here. The final then returns an explicit promise by calling getArticles() again. This shows that you're not limited to built in derived promises, but can also return promises generated by other sources midstream. This is powerful since it allows us to integrate external and internal promises in the same continuous chain.


Error handling can be added through catch methods. You can either add a granular catch handler to deal with specific promises or you can add a single catch all at the end. The main difference is that specific error handlers midstream will handle the error and let subsequent then handlers carry on as if nothing happened – unless you return a rejected promise or throw an error from the catch function. The catch function may seem like a different beast, but it's really just a then method in disguise. In fact the then method actually supports two callbacks, so it's full potential is

```js
.then(function(){},function(){})

```
The fist callback is the success handler described above and the second callback is the error handler.

Since the dual callback situation is somewhat cumbersome, catch was defined as a wrapper that maps to
```js
.then(null,function(){})
```
Finally, here is an example with both a then handler and a catch handler
```js
articleService.getArticles('angular')
    .then(function(articles){
    })
    .catch(function(e){
       console.log(e);
    })
```
<p data-height="268" data-theme-id="0" data-slug-hash="MaxXgp" data-default-tab="result" data-user="walkingtree" class='codepen'>See the Pen <a href='http://codepen.io/walkingtree/pen/MaxXgp/'>MaxXgp</a> by Walking Tree (<a href='http://codepen.io/walkingtree'>@walkingtree</a>) on <a href='http://codepen.io'>CodePen</a>.</p>
<script async src="//assets.codepen.io/assets/embed/ei.js"></script>
